server:
  port: 1304
  servlet:
    context-path: /pjone-server
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbname?serverTimezone=Asia/Shanghai
    username: username
    password: password
